card without check
IvgenV/ThesisProject pull request #21
Opened 2021-08-30 16:23 UTC by IvgenV

2021-09-01 08:46 UTC, yaskevich-dev requested changes

2021-09-01 08:46 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/adapter/ToFragmentNews.kt
> +    fun SharedPreferences(card:MaterialCardView,title:String)
функции строго с маленькой буквы, подробнее [здесь](https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html)

2021-09-01 08:46 UTC, yaskevich-dev commented on app/src/main/res/layout/news_item_for_recyclerview.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
`ConstraintLayout` уже тут лишний получается, добавляет лишь излишнюю вложенность и время рендра

2021-09-01 08:46 UTC, yaskevich-dev commented on app/src/main/res/layout/news_item_for_recyclerview.xml
> +    </com.google.android.material.card.MaterialCardView>
- надо добавить отступы между краями `CardView` и тестом/иконками (см подробнее какие где отступы рекомендуются [здесь](https://material.io/components/cards#specs))
- картинку наоборот на всю ширину (без отступов, но с сохранением пропорций, см параметр `scaleType` для `ImageView`)
- фона у заголовка не должно быть
- текст "читать новость полностью" излишен (по клику на карточку открывать страницу новости)

2021-09-01 08:46 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/adapter/NewsAdapter.kt
> +                            holder.expand.visibility = View.INVISIBLE
можно использовать котлиновский метод `.isVisible = true/false` и/или `.isInvisible = true/false`

2021-09-01 08:46 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/adapter/NewsAdapter.kt
> +    }
как параметр сюда можно передавать сразу `TextView`

2021-09-02 14:16 UTC, yaskevich-dev requested changes

2021-09-02 14:16 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentNews.kt
> +        key = viewModel.key
не вижу смысла тут использовать локальную переменную, её в целом можно опустить
также используй более понятные названия, это я так понимаю какая то инфа связанная с пользователем, верно? тогда и назови её соответственно, потому как то как ты будешь её использовать не объясняет что в ней хранится

2021-09-07 08:46 UTC, yaskevich-dev requested changes

2021-09-07 08:46 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/ReadNews.kt
> +data class ReadNews(var newsList:MutableList<String>)
можно опустить эту модель и непосредственно использовать список вместо неё

2021-09-07 08:46 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/data/sharedPreferences/SharedPreferencesNews.kt
> +        val sharedPreferences: SharedPreferences = context.getSharedPreferences(shPrNews,Context.MODE_PRIVATE)
получаешь этот объект дважды, проще его вывести как переменную на уровень класса и хранить вместо `context`

2021-09-07 08:46 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/data/sharedPreferences/SharedPreferencesNews.kt
> +        readNews = gson.fromJson(sharedPreferences.getString(key,str),ReadNews::class.java)
опять же, получаешь список много раз, можно или вывести в отдельный метод или в переменную на уровень класса

2021-09-07 08:46 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/data/sharedPreferences/SharedPreferencesNews.kt
> +        readNews = gson.fromJson(sharedPreferences.getString(key,listOfTitle), ReadNews::class.java)
тут как раз можно использовать метод получения списка

2021-09-07 08:46 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentNews.kt
> +        viewModel.initialNews()
можно объединить в метод `getNews()`

2021-09-07 08:46 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/viewmodel/ViewModel.kt
> +    val sharedPreferencesNews = Dependencies.getSharedPreferencesNews()
лучше использовать слабую ссылку, так как там храниться `context` (см. строчку выше)

2021-09-07 08:46 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/viewmodel/ViewModel.kt
> +    }
этот метод не используется, он ещё нужен?

2021-09-07 08:46 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/viewmodel/ViewModel.kt
> +                    listNews?.forEach {
тут классно использовать метод kotlin `map`, посмотри если ещё им не пользовался

2021-09-07 08:46 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/viewmodel/ViewModel.kt
> +                    progress.value = View.INVISIBLE
можно вынести за `if`, вызывать после, раз при обоих условиях одинаково

2021-09-07 08:52 UTC, yaskevich-dev requested changes

2021-09-07 08:52 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/data/sharedPreferences/SharedPreferencesNews.kt
> +        editor.apply()
можно сохранять только если внесли изменения, в остальных случает излишне

2021-09-07 10:11 UTC, IvgenV commented on app/src/main/java/thesis_project/data/sharedPreferences/SharedPreferencesNews.kt
> +        readNews = gson.fromJson(sharedPreferences.getString(key,listOfTitle), ReadNews::class.java)
?

2021-09-07 10:12 UTC, IvgenV commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentNews.kt
> +        viewModel.initialNews()
?

2021-09-07 10:24 UTC, IvgenV commented on app/src/main/java/thesis_project/presentation/viewmodel/ViewModel.kt
> +                    listNews?.forEach {
?

2021-09-07 10:25 UTC, IvgenV commented on app/src/main/java/thesis_project/data/sharedPreferences/SharedPreferencesNews.kt
> +        readNews = gson.fromJson(sharedPreferences.getString(key,listOfTitle), ReadNews::class.java)
?

2021-09-07 10:25 UTC, IvgenV commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentNews.kt
> +        viewModel.initialNews()
?

2021-09-07 10:25 UTC, IvgenV commented on app/src/main/java/thesis_project/presentation/viewmodel/ViewModel.kt
> +                    listNews?.forEach {
?

2021-09-08 11:04 UTC, yaskevich-dev approved these changes

2021-09-09 14:51 UTC, merged