add bottom navigation
IvgenV/ThesisProject pull request #24
Opened 2021-09-14 12:19 UTC by IvgenV

2021-09-15 08:59 UTC, yaskevich-dev requested changes
Также необходимо все неиспользуемые компоненты (разметки, классы, ресурсы). Например FragmentStart, fragment_start.xml и тд. Можно воспользоваться инструментом Android Studio Analyze -> Run insection by name -> unused resources или провести полный анализ ошибок Analyze -> Inspect code

2021-09-15 08:59 UTC, yaskevich-dev commented on app/src/main/res/layout/fragment_start.xml
> +        android:theme="@style/Theme.Thesis_Project"
тут есть разница в цвете или можно этот параметр опустить?

2021-09-15 16:37 UTC, yaskevich-dev requested changes
1. Не все неиспользованные ресурсы удалены.
2. Ошибка в работе drawer и кнопки back:
- Открой drawer
- Нажми кнопку back
-> drawer должен закрыться, экран остается, больше ничего
3. Если профиль на весь экран, настройки может тоже надо также?

2021-09-15 16:37 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentProfile.kt
> +        bottomNavigationView.visibility = View.VISIBLE
если ты показываешь `bottomNavigationView` в методе `onCreateView` тогда и прятать нудно в обратном методе `onDestroyView`

2021-09-15 16:37 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/StartActivity.kt
> +        }
Можно упростить например так:

```
when (it.itemId) {
       R.id.rateBottomMenu -> R.id.fragment_rate
       R.id.atmBottomMenu -> R.id.fragment_atm
       R.id.infoboxBottomMenu -> R.id.fragment_infoBox
       R.id.newsBottomMenu -> R.id.fragment_news
       else -> null
}?.let { destinationId ->
    navController.graph.startDestination = destinationId
    navController.navigate(destinationId)
    true
} ?: false

2021-09-15 16:37 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentProfile.kt
> +                requireActivity().supportFragmentManager.popBackStack()
опять же тут в обоих случаях одни и те же действия, нудно ли дублировать?

2021-09-15 16:37 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentProfile.kt
> +                navigationView.menu.getItem(0).isChecked = false
эта строчка нужная? вроде как и без неё работает

2021-09-16 11:17 UTC, yaskevich-dev requested changes
Исправить проблемы описанные в комментах

2021-09-16 11:17 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentProfile.kt
>          email.text = myViewModel.email
инициализацию хватит сделать один раз, тогда нет необходимости использовать метод `onStart` для этого, лучше использовать `onViewCreated`, а уже настройку или то что важно именно каждый раз при возвращении к приложению делать

2021-09-16 11:17 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentSetting.kt
> +                navigationView.menu.getItem(1).isChecked = false
эта строчка нужная? вроде как и без неё работает

2021-09-16 11:17 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/BaseStartFragment.kt
> +                if(snackBar.isShown){
тут всегда будет `false`, потому как инициализация прямо перед этим произошла, а `show` не вызывался

2021-09-16 11:17 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentProfile.kt
> +class FragmentProfile : Fragment() {
для экранов в шторке можно что-то вроде базового сделать тогда фрагмента, чтобы в каждом не дублировать

2021-09-16 11:17 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentProfile.kt
> +        )
это нет смысла делать каждый раз при возвращении, то есть лучше перенести в `onViewCreated`

2021-09-16 11:17 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentSetting.kt
> +        }
то же самое про инициализацию

2021-09-16 11:17 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentSetting.kt
> +        )
это нет смысла делать каждый раз при возвращении, то есть лучше перенести в onViewCreated

2021-09-16 11:17 UTC, yaskevich-dev commented on app/src/main/res/values/strings.xml
>      <string name="workerTime">60</string>
только маленькая буква в имени ресурса!

2021-09-16 11:17 UTC, yaskevich-dev commented on app/src/main/res/values-night/themes.xml
> +    <style name="Theme.Thesis_Project_Dark" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
Почему используешь другое название темы, если она и так определена в "темной" папке?

2021-09-16 11:17 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentSetting.kt
> +            requireActivity().setTheme(R.style.Theme_Thesis_Project_Dark)
Обязательно ли менять тему?

2021-09-16 11:18 UTC, IvgenV commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentProfile.kt
> +                navigationView.menu.getItem(0).isChecked = false
без нее при возврате не снимается чек с выбранного пункта меню

2021-09-16 11:20 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentProfile.kt
> +                navigationView.menu.getItem(0).isChecked = false
так нам же и не надо с него чек снимать, мы ж на нем и должны остаться, разве нет?

2021-09-16 11:52 UTC, IvgenV commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentSetting.kt
> +                navigationView.menu.getItem(1).isChecked = false
без нее при возврате не снимается чек с выбранного пункта меню

2021-09-16 11:54 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentSetting.kt
> +                navigationView.menu.getItem(1).isChecked = false
так нам же и не надо с него чек снимать, мы ж на нем и должны остаться, разве нет?
я имею в виду не первый а вообще, тот с которого уходим, а первый и не обязательно выделен

2021-09-16 12:01 UTC, IvgenV commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentProfile.kt
> +class FragmentProfile : Fragment() {
экранов в шторке? Имеется ввиду фаргменты без bottomNavigationView?

2021-09-16 12:03 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentProfile.kt
> +class FragmentProfile : Fragment() {
ага, или делай однострочное управление этим через активити, либо просто базовый фрагмент для тех кто на весь экран

2021-09-16 15:03 UTC, IvgenV commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentSetting.kt
> +                navigationView.menu.getItem(1).isChecked = false
мыж когда ходим по менюшкам drawerLayout пункт выделятся при нажатии, если не переопределить кнопку назад, то все сбрасывается, но шторка не закрывается, поэтому переопределена кнопка назад во фрагментах на которые идет переход с DrawerLayout, без этого нормально не работает если я конечно тебя понял.

2021-09-16 15:24 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/FragmentSetting.kt
> +                navigationView.menu.getItem(1).isChecked = false
аа всё я поняла, сори, перепутала с другим меню

2021-09-17 10:11 UTC, yaskevich-dev requested changes
1. см. комменты
2. выбор темы не сохраняется после перезапуска аппы
3. краш на банкоматах
4. <img width="494" alt="Screenshot 2021-09-17 at 12 23 10" src="https://user-images.githubusercontent.com/54890098/133766220-1e9bb445-fc45-4d06-a4fd-e924cfcdab08.png">
5. <img width="494" alt="Screenshot 2021-09-17 at 12 23 16" src="https://user-images.githubusercontent.com/54890098/133766234-2a0daa39-f752-4321-8d71-7096f8f79ac7.png">

2021-09-17 10:11 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/StartActivityControlInterface.kt
> +    fun setStartTheme():Boolean
а здесь наоборот `get`

2021-09-17 10:11 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/BaseStartDrawerLayoutFragments.kt
> +    var startActivity: StartActivityControlInterface? = null
можно также использовать слабую ссылку
> val startActivity: StartActivityControlInterface by lazy { this.requireActivity() as StartActivityControlInterface }

2021-09-17 10:11 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/BaseStartFragments.kt
> +        callbackBackPressed.isEnabled = false
если включаем в `onResume`, то и выключать надо в парном методе `onPause`

2021-09-20 12:17 UTC, yaskevich-dev requested changes

2021-09-20 12:17 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/StartActivity.kt
> +            drawerLayout.closeDrawer(GravityCompat.START)
это можно вынести на уровень выше

2021-09-20 12:17 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/StartActivity.kt
> +        )
про snacker почитай комментарий выше

2021-09-20 12:17 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/StartActivityControlInterface.kt
> +    fun checkDrawerMenuBaseStartNext()
нужны ли эти методы в интерфейсе?

2021-09-20 12:17 UTC, yaskevich-dev commented on app/src/main/res/drawable-night/ic_share.xml
> +</vector>
для векторных изображений не обязательно добавлять ресурс другого цвета, достаточно указать атрибут `tint` для задания цвета в элементе `ImageView`

2021-09-20 12:20 UTC, yaskevich-dev requested changes
1. см. комменты
2. на странице новости нет навигации
3. фон у web view белый при темной теме

2021-09-20 12:59 UTC, IvgenV commented on app/src/main/java/thesis_project/presentation/ui/start/StartActivity.kt
> +            drawerLayout.closeDrawer(GravityCompat.START)
не понял если честно что имеется ввиду

2021-09-20 13:03 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/StartActivity.kt
> +            drawerLayout.closeDrawer(GravityCompat.START)
ты выполняешь эту проверку (`drawerLayout.isOpen`) и в методе `checkDrawerMenuBaseStart` и в `checkDrawerMenuBaseStartNext`, можно делать это один раз и до вызова этих методов

2021-09-20 13:14 UTC, IvgenV commented on app/src/main/res/drawable-night/ic_share.xml
> +</vector>
вот тут тоже не ясно, tint добавить и  убрать из ic_share атрибут fillColor?

2021-09-20 13:23 UTC, IvgenV commented on app/src/main/java/thesis_project/presentation/ui/start/StartActivity.kt
> +            drawerLayout.closeDrawer(GravityCompat.START)
а точно

2021-09-20 13:26 UTC, IvgenV commented on app/src/main/java/thesis_project/presentation/ui/start/StartActivity.kt
> +        )
в смысле перенести создание перед вызовом в метод checkDrawerMenuBaseStart?

2021-09-20 14:36 UTC, yaskevich-dev commented on app/src/main/java/thesis_project/presentation/ui/start/StartActivity.kt
> +        )
создаем/инициализируем там где показываем

2021-09-20 14:39 UTC, yaskevich-dev commented on app/src/main/res/drawable-night/ic_share.xml
> +</vector>
`tint` у `ImageView` позволяет задать картинке другой цвет, в не зависимости от того какое значение tint у самой картинки. У тебя получается сейчас ситуация что абсолютно одинаковые две картинки хранятся только с разным значением tint, поэтому есть смысл не дублировать картинки а задача цвет динамически в `ImageView`

2021-09-20 15:08 UTC, yaskevich-dev requested changes
1. см комментарии
2. фон `web view` в темной теме - белый

2022-07-17 19:46 UTC, closed without merging

2022-07-17 19:46 UTC, IvgenV commented
rggf